### ISSUE TITLE
Stack dump error

### ISSUE THREAD

**Issue by artemneskorodov** [asssh52/stack_faulted#5]
In dump the data pointer in stack structure is checked after printing the elements. This may cause a problem if broken stack is used.

Example of code which causes segmentation fault:
`int main(){`
`    Stack_t stk = {};`
`    if(StackCtor(&stk) != OK)`
`        return EXIT_FAILURE;`
`    stk.data = NULL;`
`    printf("Push try\n");`
`    StackPush(&stk, 5);`
`    printf("Pushed\n");`
`    StackDtor(&stk);`
`}`

**Comment by asssh52** [comment]
thanks for this comment, I will put some work into this
